name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    env:
      PACKAGE_NAME: ros2viz
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2

      - name: Install Poetry
        run: pip3 install poetry

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

      - name: Lint by Flake8
        run: poetry run flake8 tests ${PACKAGE_NAME}

      - name: Format by Black
        run: poetry run black --check tests ${PACKAGE_NAME}

      - name: Test by pytest
        run: poetry run pytest -v tests ${PACKAGE_NAME}

